### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by gnmarten** [oliverguhr/fullstop-deep-punctuation-prediction#1]
How to use beyond info on card? https://huggingface.co/oliverguhr/fullstop-punctuation-multilang-large/tree/main

from transformers import AutoTokenizer, AutoModelForTokenClassification
tokenizer = AutoTokenizer.from_pretrained("oliverguhr/fullstop-punctuation-multilang-large")
model = AutoModelForTokenClassification.from_pretrained("oliverguhr/fullstop-punctuation-multilang-large")

thanks in advance

EDIT: nevermind, I found a related issue on Github

huggingface/hub-docs#11

**Comment by oliverguhr** [comment]
Hi @gnmarten,
thanks for the feedback. I added the sample code to the model card.
Just that you know: The pipeline code will only process the first 512 token of your input text and truncate the rest.
