### ISSUE TITLE
Issues with CUDA , how to run on CPU only? 

### ISSUE THREAD

**Issue by vitotitto** [oliverguhr/fullstop-deep-punctuation-prediction#10]
Hi guys, I have an issue using CUDA on my machine, how can I tell the model to use CPU only? 

thank you very much

**Comment by oliverguhr** [comment]
Hi @vitotitto ,
for inference you can use the [lib that I wrote here](https://github.com/oliverguhr/deepmultilingualpunctuation). It automaticlly checks if you have a GPU and uses the cpu otherwhise. If you don't want to use your GPU you have two options:

1. run  ```export CUDA_VISIBLE_DEVICES="0"``` to disable the gpu (I did not test this) 

or

2. install [pytorchs cpu only version](https://pytorch.org/get-started/locally/)

**Comment by oliverguhr** [comment]
Please feel free to reopen if you have any issues
