### ISSUE TITLE
what is this model field 

### ISSUE THREAD

**Issue by Body123** [oliverguhr/fullstop-deep-punctuation-prediction#14]
hello 
what is this model field  
I am training in new language and I couldn't know what to put inside it 
![55](https://user-images.githubusercontent.com/24945076/220172426-c72802cb-496d-4c2e-a067-cc5618533200.jpg)

another question in the tutorial I think there is conflict between those instructions 
![555](https://user-images.githubusercontent.com/24945076/220172443-0f0c7e5b-aa66-4a16-a1e3-c770fc450399.jpg)

thanks

**Comment by oliverguhr** [comment]
The model field is the name of the base model that you use. Depending on your language, pick one from huggingfaces model hub. 

Regarding your second question: Yes the instructions where wrong here. I fixed this and added a note. 

Thanks for reporting that issue @Body123
