### ISSUE TITLE
What is the best model configuration to use?

### ISSUE THREAD

**Issue by RizkiNoor16** [oliverguhr/fullstop-deep-punctuation-prediction#17]
I have already trained and fine-tuned using both my native language and the dataset (sh download-dataset.sh). However, both outputs produced results that are not appropriate, as shown below
I have followed all the steps and used the provided configuration as well as modifying some configurations, but I'm still getting the same results. Could you help me with how to address this?"

for NLG Dataset :
from deepmultilingualpunctuation import PunctuationModel

model = PunctuationModel(model='models/xlm-roberta-base-en-1-task2/final')
text = "My name is Clara and I live in Berkeley California "
result = model.restore_punctuation(text)
print(result)
#MynameisClaraandIliveinBerkeleyCalifornia

---------------------------------------------------------------------------------------------------------------------------
For my native languange
from deepmultilingualpunctuation import PunctuationModel

model = PunctuationModel(model='models/xlm-roberta-base-id-1-task2/final')
text = "Apakah kamu sudah makan"
result = model.restore_punctuation(text)
print(result)
#Apakahkamusudahmakan

**Comment by oliverguhr** [comment]
Hi @RizkiNoor16,
thanks for your feedback. Can you publish your model on Hugging Face, so I can check that?
Without the code, data and model I cannot reproduce the error.

Best,
Oli

**Comment by RizkiNoor16** [comment]
Thank you for responding to my message. 
Below is the model that I trained using native language data for punct-id and using the provided SEPP NLG data for punct-en.

for my native languange : Rizkinoor16/punct-id
for seep nlg data : Rizkinoor16/punct-en

**Comment by oliverguhr** [comment]
It looks like the labels are not defined. This is a manual step that might be not in the tutorial yet.

Assuming you have the same labels, you need to replace the label to id and id to label config here:

https://huggingface.co/Rizkinoor16/punct-id/blob/7d7d287cfbd21bc419866377243a380a42e45ec0/config.json#L13

with this:

https://huggingface.co/oliverguhr/fullstop-punctuation-multilang-large/blob/main/config.json#L13

Then the inference code should work. 

I did send you a pull request on HuggingFace.

Best,
Oli

**Comment by RizkiNoor16** [comment]
thank you so much sir @oliverguhr
