### ISSUE TITLE
Publicliy available code

### ISSUE THREAD

**Issue by talipturkmen** [oliverguhr/fullstop-deep-punctuation-prediction#2]
Hello, 
I've enjoyed reading your paper "FullStop: Multilingual Deep Models for Punctuation Prediction". 
In the paper, you stated that your code is publicly available. But in the repo, I couldn't see it. Do you plan to share it?

Kind regards

**Comment by oliverguhr** [comment]
Hello @talipturkmen, I very sorry - this task is way to long on my todo list. I will publish this in the next two days.

Best Regards,
Oli

**Comment by oliverguhr** [comment]
I finally uploaded the code. In case you have any questions just respond or open a new issue.
