### ISSUE TITLE
Performance differences

### ISSUE THREAD

**Issue by gnmarten** [oliverguhr/fullstop-deep-punctuation-prediction#3]
with German sentences, the model seems to perform better on the huggingface card than elsewhere

Huggingface.co hosted inference API output is correct, elsewhere (Colab), the same example hiccups on Umlaut-characters (or nearby).

`
 man merkt ja schon in den ersten Sä,tzen,,, dass dieser Halbexot mit der Patentanwältin sch.mus.t.
`

my code
```
from transformers import pipeline

pipe = pipeline("token-classification", "oliverguhr/fullstop-punctuation-multilang-large")
text ="man merkt ja schon in den ersten Sätzen dass dieser Halbexot mit der Patentanwältin schmust"
output_json = pipe(text)
output_json
s = ''

for n in output_json:
  result = n['word'].replace('▁',' ') + n['entity'].replace('0','')
  s += result
s
```

PS: thanks for all your work and for inquiring about the 512-characters PyTorch limit :-)

**Comment by oliverguhr** [comment]
Well, the inference is rather tricky. Are you trying to process longer (>512 Token) texts?

**Comment by gnmarten** [comment]
I tried both with longer and short text, identical results.

**Comment by oliverguhr** [comment]
I am currently preparing a 
python package that allows to process texts of any length. This code should give you the same results for long and short texts. ETA: Next Week.

**Comment by oliverguhr** [comment]
I released a  python lib for inference, it should solve the problems.

```
pip install deepmultilingualpunctuation
```

```
from deepmultilingualpunctuation import PunctuationModel

model = PunctuationModel()
text = "My name is Clara and I live in Berkeley California Ist das eine Frage Frau Müller"
result = model.restore_punctuation(text)
print(result)
```

**Comment by gnmarten** [comment]
yes, results are now top-notch. thank you so much for this speedy intervention and very convenient solution! (might want to signal that sentencepiece module is required)

**Comment by oliverguhr** [comment]
Ahh, sentencepiece is a dependency of transformers and for some reason they do not include sentencepiece.
