### ISSUE TITLE
Missing datasets

### ISSUE THREAD

**Issue by ReneDorsch** [oliverguhr/fullstop-deep-punctuation-prediction#4]
Hello Oliver,

thank you for working on punctuation. 
I tried to execute the published scripts, but unfortunatley the datasets.py file is missing. 
Could you upload it?

With best regards
Rene

**Comment by oliverguhr** [comment]
Hi Rene,
oops this is a missing dependency. You can fix this by installing ```datasets```.

```bash
pip install datasets
```

**Comment by oliverguhr** [comment]
I added the datasets lib to the requirements file. Should be fine now.
