### ISSUE TITLE
how to train in another languages?

### ISSUE THREAD

**Issue by YusufCandraArif** [oliverguhr/fullstop-deep-punctuation-prediction#5]
Thank you for this amazing project.
Is it possible to be trained in another language, for example Mandarin? Thank you.

**Comment by oliverguhr** [comment]
Hi @YusufCandraArif,
basically you would need to create a dataset for your language in the same format, as the SEPP NLG task that we build this model for. [You can find the details here.](https://sites.google.com/view/sentence-segmentation) 

After that you need to add a config entry for your task in [this file](https://github.com/oliverguhr/fullstop-deep-punctuation-prediction/blob/main/model_final_suite_task2.json). After this you can start the training via:

``` 
python model_test_suite.py 2
``` 

And you are done :) Typically, some issues appear on the way. If you have any questions drop me a line or open a issue.

**Comment by oliverguhr** [comment]
Thanks to @jordimas we have a how to guide on this now:
https://github.com/oliverguhr/fullstop-deep-punctuation-prediction/blob/main/other_languages/readme.md

**Comment by YusufCandraArif** [comment]
Thank you Sir @oliverguhr
